_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 55
                - 95
            "2":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 55
                - 95
            "3":
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.12.9
            "5": 0.19.9
            "6": 4.50.3
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
batch_size:
    value: 128
max_tokens_per_step:
    value: 1024
model:
    value: deepseek-r1-7b
num_steps:
    value: 5
